FROM apache/airflow:2.6.3-python3.8

# Switch to root to install system packages and change permissions
USER root
RUN apt-get update && apt-get install -y postgresql-client

# Copy entrypoint and give permission
COPY entrypoint.sh /opt/airflow/entrypoint.sh
RUN chmod +x /opt/airflow/entrypoint.sh

# Switch back to airflow user
USER airflow

# Install Python requirements
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
